server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://${DB_CONNECTION_STRING}/loan_eligibility
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        generate_statistics: true
        ddl-auto: validate
        jdbc:
          time_zone: UTC
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
