server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${DB_CONNECTION_STRING:localhost:5432}/loan
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:12345}
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        generate_statistics: false
        ddl-auto: validate
        jdbc:
          time_zone: UTC
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect