DO
$do$
BEGIN

   IF NOT EXISTS (
      SELECT FROM PG_USER  -- SELECT LIST CAN BE EMPTY FOR THIS
      WHERE  USENAME = 'loan_user') THEN
      CREATE USER LOAN_USER WITH PASSWORD '${loan_db_pass}';
   END IF;

   ALTER USER LOAN_USER WITH PASSWORD '${loan_db_pass}';

END
$do$;