apiVersion: apps/v1
kind: Deployment
metadata:
  name: loan-eligibility
  labels:
    app: loan-eligibility
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loan-eligibility
  template:
    metadata:
      annotation:
        ad.datadoghq.com/loan-eligibility.logs: '[{"source":"eks","service":"loan-eligibility"}]'
      labels:
        app: loan-eligibility
    spec:
      containers:
        - name: loan-eligibility
          image: ${SUBENV_LOAN_ELIGIBILITY_SERVICE_CONTAINER}
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 3
            timeoutSeconds: 1
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 5
            periodSeconds: 60
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: "128Mi"
              cpu: "0.1"
            limits:
              memory: "256Mi"
              cpu: "1"
          env:
            - name: DB_CONNECTION_STRING
              value: ${SUBENV_DB_CONNECTION_STRING}
            - name: DB_USER
              value: loan_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: loan-db-secret
                  key: dbpass