apiVersion: batch/v1
kind: Job
metadata:
  name: loan-eligibility-service-init-db-job
spec:
  template:
    spec:
      containers:
      - name: loan-eligibility-service-init-db-job
        image: alpine:3
        command: ["/bin/sh","-c"]
        args:  
            - apk --update add postgresql-client && rm -rf /var/cache/apk/*;
              echo running_job;
              psql ${connection_string} -tc "select 'create database loan_eligibility' where not exists (select from pg_database where datname='loan_eligibility')" | xargs -I % psql ${connection_string} -c %;
              psql ${connection_string_rds} -f /script/output.sql;
              psql ${connection_string_rds} -f /schema_script/revoke-schema.sql;
        volumeMounts:
          - name: sql-command
            mountPath: /script/
          - name: schema-command
            mountPath: /schema_script
      volumes:
        - name: sql-command
          configMap:
            name: loan-initdb-sql
        - name: schema-command
          configMap:
            name: loan-schema-sql
      restartPolicy: Never