apiVersion: batch/v1
kind: Job
metadata:
  name: loan-eligibility-service-init-db-job
spec:
  template:
    spec:
      containers:
      - name: loan-eligibility-service-init-db-job
        image: alpine:3
        command: ["/bin/sh","-c"]
        args:  
            - apk --update add postgresql-client && rm -rf /var/cache/apk/*;
              echo running_job;
              psql ${connection_string} -tc "select 'create database loan_eligibility' where not exists (select from pg_database where datname='loan_eligibility')" | xargs -I % psql ${connection_string} -c %;
              psql ${connection_string_rds} -tc "select 'create user loan_user' where not exists (select from pg_catalog.pg_roles where rolname = 'loan_user')" | xargs -I % psql ${connection_string_rds} -c %;
              psql ${connection_string_rds} -tc "alter user loan_user with password '${loan_db_pass}'" | xargs -I % psql ${connection_string_rds} -c %;
              psql ${connection_string_rds} -tc "grant all privileges on database loan_eligibility to loan_user" | xargs -I % psql ${connection_string_rds} -c %;
              psql ${loan_user_connection_string} < /script/create-schema.sql
        volumeMounts:
          - name: sql-command
            mountPath: /script/
      volumes:
        - name: sql-command
          configMap:
            name: loan-initdb-sql
      restartPolicy: Never