apiVersion: batch/v1
kind: Job
metadata:
  name: loan-eligibility-service-init-db-job
spec:
  template:
    spec:
      containers:
      - name: loan-eligibility-service-init-db-job
        image: alpine:3
        command: ["/bin/sh","-c"]
        args:  
            - apk --update add postgresql-client && rm -rf /var/cache/apk/*; 
              echo running_job;
              psql ${connection_string} -tc \"select 'create database loan_eligibility' where not exists (select from pg_database where datname='loan_eligibility');\" | xargs -I % psql ${connection_string} -c '%';
      restartPolicy: Never