DO
$SUBENV_PG_FUNC
BEGIN
   IF NOT EXISTS (
      SELECT FROM PG_USER
      WHERE  USENAME = 'loan_user') THEN
      CREATE USER LOAN_USER WITH PASSWORD '${SUBENV_loan_db_pass}';
   END IF;

   ALTER USER LOAN_USER WITH PASSWORD '${SUBENV_loan_db_pass}';
END
$SUBENV_PG_FUNC;