name: Build and Deploy to AWS Cloud

on:
  push:
    branches:
      - master

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  setup-build-push-to-ecr:
    name: Setup, Build, Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/hello-world-docker-action@v1
      - name: Build
        run: docker build -f ./toolchain-containers/Dockerfile.gradle . -q